### ISSUE TITLE
RT or Issues

### ISSUE THREAD

**Issue by kevindawson** [CPAN-API/metacpan-client#11]
the link in MetaCPAN -> https://rt.cpan.org/Public/Dist/Display.html?Name=MetaCPAN-Client

not here :(

**Comment by xsawyerx** [comment]
It should be Github issues. Yes.

**Comment by mickeyn** [comment]
Let's stick to Github. closing this for now.

**Comment by xsawyerx** [comment]
To close this, I'll add the Meta variables and release a quick version with it. I'll also move the RT tickets.
