### ISSUE TITLE
Raw Query construction for Request class

### ISSUE THREAD

**Issue by kentfredric** [CPAN-API/metacpan-client#22]
This really aught to be a discussion of some kind, because I don't *really* know what I'm doing here.

`request->ssearch()` is presently poorly designed for doing raw queries. 

You can hack around it with 

```perl
request->ssearch('author', { bogus => 1 }, { %raw_query_here });
```
And it works because you can stuff `{body => }` there and blow away the annyoingly constrictive generated one.

But its ugly, and the function is not very obvious. You need the `bogus` stuff because without it, it simply breaks due to the generated query having `$args != 1`

I've considered various ways of hacking around it, to make the interface slightly more usable, for instance: 

> https://gist.github.com/kentfredric/22266f846eb6003dc842

But that solution strikes me as pretty dodgy because of the magical behaviour that is dependent on the value of `$args`

I even considered 
```diff
diff --git a/lib/MetaCPAN/Client/Request.pm b/lib/MetaCPAN/Client/Request.pm
index 3c58fcf..2c20bb5 100644
--- a/lib/MetaCPAN/Client/Request.pm
+++ b/lib/MetaCPAN/Client/Request.pm
@@ -158,6 +158,9 @@ sub _build_query_rec {
     ref $args eq 'HASH' or croak 'query args must be a hash';
 
     my %query = ();
+
+    return \%query if not keys %{$args};
+
     my $basic_element = 1;
 
   KEY: for my $k ( qw/ all either not / ) {
```

But really, that's the same problem all over again, magical behaviour with a magic token.

I think this, slightly more complex approach would be better: 

https://gist.github.com/kentfredric/65295334188a7fba4024

Simply because it keeps the existing API exactly the same, doesn't introduce any magical token behaviour, and gives a useful raw search at the same time.

Incidentally, that approach was the first one I tried, and the other ones are later ideas I had after I realised you **could** already pass custom params.

**Comment by mickeyn** [comment]
this is supported in modern versions
