### ISSUE TITLE
Add ability to specify fields to be returned

### ISSUE THREAD

**Issue by xsawyerx** [CPAN-API/metacpan-client#25]
*(This was originally RT [#99499](https://rt.cpan.org/Ticket/Display.html?id=99499).)*

When getting large data sets, it's very helpful to be able to pare down the number of fields returned.  It would be great to be able to do this via MetaCPAN::Client.

ie it's the difference between http://api.metacpan.org/module/Moose?fields=version and http://api.metacpan.org/module/Moose

**Comment by mickeyn** [comment]
@oalders: done in 1.009000

you can now do either:
my $module = $mcpan->module('Moose', { fields => "version,author" });
my $module = $mcpan->module('Moose', { fields => [qw/version author/] });

cheers

**Comment by oalders** [comment]
@mickeyn++
