### ISSUE TITLE
Test::Requires required modules cause a BAIL_OUT

### ISSUE THREAD

**Issue by xsawyerx** [CPAN-API/metacpan-client#26]
Apparently when the modules aren't available, it just causes a BAIL_OUT. Example:

    t/ua_trap.t ............... Bailout called.  Further testing stopped:  Test requires module 'WWW::Mechanize::Cached' but it's not found
    FAILED--Further testing stopped: Test requires module 'WWW::Mechanize::Cached' but it's not found

It doesn't skip. :(

**Comment by haarg** [comment]
Test::Requires will trigger a bailout on missing modules if RELEASE_TESTING is set.  For normal users, it will skip properly.

**Comment by xsawyerx** [comment]
D'oh.

Thanks :)
