### ISSUE TITLE
examples/all_favorite_dists.pl~  in distribution

### ISSUE THREAD

**Issue by szabgab** [CPAN-API/metacpan-client#29]
I can't even find ```examples/all_favorite_dists.pl``` in the repo.

OTOH I see ```all_favorite_counts_per_dist.pl``` in the repo but not on CPAN.

https://metacpan.org/release/MetaCPAN-Client

**Comment by mickeyn** [comment]
thanks for catching, will fix it.

**Comment by mickeyn** [comment]
cleaned in the latest release
