### ISSUE TITLE
CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by bk** [CPAN-API/metacpan-client#32]
I was assigned this repo for the April [CPAN Pull Request Challenge][1] and am wondering which kinds of contributions you would like to receive.

[1]: http://blogs.perl.org/users/neilb/2014/12/take-the-2015-cpan-pull-request-challenge.html

**Comment by mickeyn** [comment]
Hi, great to have you on board.

The answer depends on how deep you want to get involved :)

One thing on my TODO list is to support simplified syntax for the ES filters we support in 'all' queries (right now it's raw syntax, but I would like it to take the same syntax we support in 'complex' queries).

What do you say?

**Comment by bk** [comment]
That sounds quite doable. I'm on it!

**Comment by mickeyn** [comment]
awesome, let me know if you need any help ;)
