### ISSUE TITLE
Add mirrors and/or rating?

### ISSUE THREAD

**Issue by oalders** [CPAN-API/metacpan-client#33]
There is a little known type in the index for CPAN mirrors:

http://api.metacpan.org/mirror/_mapping

It's there, so it may be worth adding.  There is also rating: http://api.metacpan.org/rating/_mapping  I'm not sure how useful it is, but I guess you can use it to find changes in favorites for some arbitrary period of time.

**Comment by mickeyn** [comment]
added to master, will release later today.

thanks for the tip ;)

**Comment by mickeyn** [comment]
released: https://metacpan.org/release/MICKEY/MetaCPAN-Client-1.012000

@oalders :+1:

**Comment by mickeyn** [comment]
closed by accident :), please let me know if that covers what you wanted.

**Comment by oalders** [comment]
@mickeyn that was lightning faaaaaaast. :+1: Thanks!!!
