### ISSUE TITLE
MetaCPAN::Client does not cache results with WWW::Mechanize::Cached

### ISSUE THREAD

**Issue by melezhik** [CPAN-API/metacpan-client#37]
Hi! Not sure if this should address to MetaCPAN::Client directly , but it seems caching does not happen from time to time. Sometimes it works fine and sometimes client try to download stuff from internet over and over again.

My set up:

```
            my $meta_client = MetaCPAN::Client->new(
              ua => HTTP::Tiny::Mech->new(
                mechua => WWW::Mechanize::Cached->new(
                  cache => CHI->new(
                    driver   => 'File',
                    root_dir => "$ENV{HOME}/.swatman/metacpan/cache/",
                  ),
                ),
              ),
            );

```

**Comment by melezhik** [comment]
I am afraid I hurry to open this one. This is not a bug, at least I probably know now what happening ...

**Comment by oalders** [comment]
@melezhik would you mind sharing what the problem was? Might be helpful to someone else.

**Comment by melezhik** [comment]
First I tried to run mojo application, where fetch some information  from metacpan using metacpan client in cache flavor so not re upload  data from internet every time, see a code snippet above.

I am not sure but sometimes caching works fine - like files representing cache exists and because of cache _an application web page_ is loaded quite fast, but sometimes it was not, first I blamed it to meta cpan client try to re-upload data from internet, ( ignoring a cache or WWW::Mechanize::Cached ignoring the cache or ... etc ) and so  slow downing the output   , but then I noticed that it is probably  impact from other piece of application like slow css resources returned from external hosts etc. I am still have not identified a real root of the issue, probably I needed to add some debug on metacpan-client / WWW::Mechanize::Cache context ( this would imply hacking into modules code then ), but I just decided to use metacpan-client  without caching and then bring caching afterwords using low level CHI approach ...

**Comment by oalders** [comment]
Thanks for the clarification.  You could try using `LWP::ConsoleLogger::Easy` if you need to debug the UserAgent.  Not sure how that will behave with caching enabled, but you can get some useful information out of it.
